- name: iOS Apps
  link: https://itunes.apple.com/us/developer/preet-kamal-minhas/id433040332
  target: _blank
- name: Android Apps
  link: https://play.google.com/store/apps/developer?id=Preet+Kamal+Minhas
  target: _blank
- name: Unity Plugins
  link: https://assetstore.unity.com/publishers/4214
  target: _blank